# Site settings
title: Seonsu
email: 
description: > # this means to ignore newlines until "baseurl:"
  My personal Go/Baduk/W&eacute;iq&iacute; blog
baseurl: "/baduk/" # the subpath of your site, e.g. /blog/
url: "http://swannodette.github.io" # the base hostname & protocol for your site
twitter_username: swannodette
github_username: swannoddetee

# Build settings
markdown: kramdown
